# .streamlit/secrets.toml

[api_keys]
SHODAN_API_KEY = "qnybI5Ut2XbDJQ2DuWn5d56EJokPGnEs"
BREACH_DIRECTORY_API_KEY = "7d93764f6bmsh81095bf18419627p1fc415jsnf6df534c0add"

GENAI_API_KEY = "AIzaSyDZjor43yqVq4bWRThkg-EraIh6vmlCw6s"
